language: node_js
notifications:
  email: false
node_js:
<<<<<<< HEAD
  - '6.4.0'
=======
  - '6.0.0'
>>>>>>> 73c87a4fbe0ffca391a5d67ff3bbd4948184ebaf
before_install:
  - travis_retry nvm install 6.0.0
  - travis_retry wget https://www.dropbox.com/s/heja4ryn45bd5wt/test.tar.gz?dl=0 -O test.tar.gz && tar xfvz test.tar.gz
env:
  global:
    - MERGE_TOKEN=7ec583e95b00bfab262215cb3bb41c5ec822951f
script:
<<<<<<< HEAD
  - npm test
=======
  - npm test
>>>>>>> 73c87a4fbe0ffca391a5d67ff3bbd4948184ebaf
